spring:
  datasource:
    url: jdbc:mysql://localhost:33306/sakila
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
